package stdio_parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 19 16:26:00 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GGEQ = 64;
  public static final int SHORT = 43;
  public static final int BAREQ = 67;
  public static final int CONST = 46;
  public static final int MM = 18;
  public static final int GG = 15;
  public static final int GE = 20;
  public static final int PLUSEQ = 58;
  public static final int SEMI = 27;
  public static final int LLONG = 53;
  public static final int DIVIDEQ = 61;
  public static final int COMMA = 32;
  public static final int DEFINE = 5;
  public static final int RPAREN = 34;
  public static final int DOTS = 10;
  public static final int LQ = 38;
  public static final int DOUBLE = 56;
  public static final int STRUCT = 37;
  public static final int LPAREN = 33;
  public static final int LL = 16;
  public static final int RQ = 39;
  public static final int LLINT = 54;
  public static final int TILDE = 48;
  public static final int LE = 21;
  public static final int UN_SIGNED = 45;
  public static final int PERCENTEQ = 62;
  public static final int FLOAT = 55;
  public static final int IFDEF = 68;
  public static final int AMPERSANDEQ = 65;
  public static final int INCLUDE = 72;
  public static final int NUMBER = 73;
  public static final int QUESTIONMARK = 42;
  public static final int SHARP = 4;
  public static final int LONG = 44;
  public static final int PLUS = 28;
  public static final int PERCENT = 40;
  public static final int DIVIDE = 31;
  public static final int EQUAL = 25;
  public static final int IFNDEF = 69;
  public static final int ASSIGN = 8;
  public static final int CHAR = 49;
  public static final int STAR = 30;
  public static final int GREATER = 13;
  public static final int EXTERN = 35;
  public static final int SHARPIF = 3;
  public static final int ELSE = 70;
  public static final int STAREQ = 60;
  public static final int LINT = 52;
  public static final int PP = 19;
  public static final int DOT = 9;
  public static final int AMPERSAND = 47;
  public static final int INT = 50;
  public static final int LDOUBLE = 57;
  public static final int EOF = 0;
  public static final int ENDIF = 71;
  public static final int MINUS = 29;
  public static final int HAT = 41;
  public static final int OR = 23;
  public static final int error = 1;
  public static final int SINT = 51;
  public static final int IF = 2;
  public static final int ID = 74;
  public static final int COLON = 26;
  public static final int RBRACKET = 7;
  public static final int BARDOT = 12;
  public static final int HATEQ = 66;
  public static final int NOTEQUAL = 24;
  public static final int LESS = 14;
  public static final int AND = 22;
  public static final int BAR = 11;
  public static final int PREF = 17;
  public static final int LBRACKET = 6;
  public static final int TYPEDEF = 36;
  public static final int LLEQ = 63;
  public static final int MINUSEQ = 59;
}

