
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 08 09:55:09 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GGEQ = 61;
  public static final int SHORT = 40;
  public static final int BAREQ = 64;
  public static final int CONST = 43;
  public static final int MM = 15;
  public static final int GG = 12;
  public static final int GE = 17;
  public static final int PLUSEQ = 55;
  public static final int SEMI = 24;
  public static final int LLONG = 50;
  public static final int DIVIDEQ = 58;
  public static final int COMMA = 29;
  public static final int DEFINE = 2;
  public static final int RPAREN = 31;
  public static final int DOTS = 7;
  public static final int LQ = 35;
  public static final int DOUBLE = 53;
  public static final int STRUCT = 34;
  public static final int LPAREN = 30;
  public static final int LL = 13;
  public static final int RQ = 36;
  public static final int LLINT = 51;
  public static final int TILDE = 45;
  public static final int LE = 18;
  public static final int UN_SIGNED = 42;
  public static final int PERCENTEQ = 59;
  public static final int FLOAT = 52;
  public static final int IFDEF = 65;
  public static final int AMPERSANDEQ = 62;
  public static final int INCLUDE = 69;
  public static final int NUMBER = 70;
  public static final int QUESTIONMARK = 39;
  public static final int LONG = 41;
  public static final int PLUS = 25;
  public static final int PERCENT = 37;
  public static final int DIVIDE = 28;
  public static final int EQUAL = 22;
  public static final int IFNDEF = 66;
  public static final int ASSIGN = 5;
  public static final int CHAR = 46;
  public static final int STAR = 27;
  public static final int GREATER = 10;
  public static final int EXTERN = 32;
  public static final int ELSE = 67;
  public static final int STAREQ = 57;
  public static final int LINT = 49;
  public static final int PP = 16;
  public static final int DOT = 6;
  public static final int AMPERSAND = 44;
  public static final int INT = 47;
  public static final int LDOUBLE = 54;
  public static final int EOF = 0;
  public static final int ENDIF = 68;
  public static final int MINUS = 26;
  public static final int HAT = 38;
  public static final int OR = 20;
  public static final int error = 1;
  public static final int SINT = 48;
  public static final int ID = 71;
  public static final int COLON = 23;
  public static final int RBRACKET = 4;
  public static final int BARDOT = 9;
  public static final int HATEQ = 63;
  public static final int NOTEQUAL = 21;
  public static final int LESS = 11;
  public static final int AND = 19;
  public static final int BAR = 8;
  public static final int PREF = 14;
  public static final int LBRACKET = 3;
  public static final int TYPEDEF = 33;
  public static final int LLEQ = 60;
  public static final int MINUSEQ = 56;
}

