
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 01 23:49:10 CEST 2014
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Aug 01 23:49:10 CEST 2014
  */
public class parser extends lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\046\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\004\004" +
    "\000\002\004\004\000\002\004\004\000\002\004\010\000" +
    "\002\004\003\000\002\016\002\000\002\014\010\000\002" +
    "\012\007\000\002\013\004\000\002\013\005\000\002\011" +
    "\004\000\002\011\007\000\002\011\006\000\002\011\012" +
    "\000\002\007\004\000\002\007\004\000\002\007\004\000" +
    "\002\010\003\000\002\010\003\000\002\005\003\000\002" +
    "\005\005\000\002\005\005\000\002\005\003\000\002\005" +
    "\005\000\002\005\002\000\002\015\006\000\002\006\003" +
    "\000\002\006\004\000\002\006\005\000\002\006\004\000" +
    "\002\006\005\000\002\006\006\000\002\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\114\000\012\007\004\022\011\023\010\024\007\001" +
    "\002\000\004\030\116\001\002\000\014\002\114\007\004" +
    "\022\011\023\010\024\007\001\002\000\022\002\ufffd\007" +
    "\ufffd\010\112\022\ufffd\023\ufffd\024\ufffd\027\056\030\055" +
    "\001\002\000\004\030\106\001\002\000\010\011\017\024" +
    "\072\030\016\001\002\000\010\011\017\024\021\030\016" +
    "\001\002\000\004\012\015\001\002\000\014\002\uffff\007" +
    "\uffff\022\uffff\023\uffff\024\uffff\001\002\000\004\012\ufff8" +
    "\001\002\000\014\002\ufffe\007\ufffe\022\ufffe\023\ufffe\024" +
    "\ufffe\001\002\000\016\004\uffe2\015\uffe2\017\uffe2\020\uffe2" +
    "\021\uffe2\030\uffe2\001\002\000\006\011\070\030\067\001" +
    "\002\000\004\012\ufffc\001\002\000\004\030\065\001\002" +
    "\000\012\004\027\015\025\020\026\030\024\001\002\000" +
    "\004\012\ufffb\001\002\000\010\004\054\012\ufff2\020\053" +
    "\001\002\000\016\004\uffdf\015\uffdf\017\uffdf\020\uffdf\021" +
    "\uffdf\030\uffdf\001\002\000\004\015\031\001\002\000\004" +
    "\005\030\001\002\000\016\004\uffde\015\uffde\017\uffde\020" +
    "\uffde\021\uffde\030\uffde\001\002\000\006\021\033\030\032" +
    "\001\002\000\004\021\034\001\002\000\016\004\uffdd\015" +
    "\uffdd\017\uffdd\020\uffdd\021\uffdd\030\uffdd\001\002\000\004" +
    "\020\035\001\002\000\012\011\017\021\uffe4\024\021\030" +
    "\016\001\002\000\014\004\027\015\025\017\044\020\045" +
    "\021\uffe9\001\002\000\004\021\043\001\002\000\006\017" +
    "\041\021\uffe6\001\002\000\012\011\017\021\uffe4\024\021" +
    "\030\016\001\002\000\004\021\uffe5\001\002\000\004\012" +
    "\uffef\001\002\000\014\006\051\011\017\021\uffe4\024\021" +
    "\030\016\001\002\000\014\011\017\015\046\021\uffe4\024" +
    "\021\030\016\001\002\000\004\021\033\001\002\000\004" +
    "\021\050\001\002\000\006\017\uffe3\021\uffe3\001\002\000" +
    "\004\021\uffe7\001\002\000\004\021\uffe8\001\002\000\012" +
    "\011\ufff7\021\ufff7\024\ufff7\030\ufff7\001\002\000\010\005" +
    "\057\027\056\030\055\001\002\000\024\002\uffeb\005\uffeb" +
    "\007\uffeb\010\uffeb\022\uffeb\023\uffeb\024\uffeb\027\uffeb\030" +
    "\uffeb\001\002\000\024\002\uffea\005\uffea\007\uffea\010\uffea" +
    "\022\uffea\023\uffea\024\uffea\027\uffea\030\uffea\001\002\000" +
    "\004\012\ufff0\001\002\000\004\005\061\001\002\000\004" +
    "\012\ufff1\001\002\000\012\011\017\021\uffe4\024\021\030" +
    "\016\001\002\000\004\021\064\001\002\000\004\012\ufff6" +
    "\001\002\000\004\015\066\001\002\000\016\004\uffdc\015" +
    "\uffdc\017\uffdc\020\uffdc\021\uffdc\030\uffdc\001\002\000\016" +
    "\004\uffe1\015\uffe1\017\uffe1\020\uffe1\021\uffe1\030\uffe1\001" +
    "\002\000\004\030\071\001\002\000\016\004\uffe0\015\uffe0" +
    "\017\uffe0\020\uffe0\021\uffe0\030\uffe0\001\002\000\006\025" +
    "\076\030\065\001\002\000\012\004\027\015\025\020\026" +
    "\030\075\001\002\000\004\012\ufffa\001\002\000\006\004" +
    "\054\012\ufff2\001\002\000\010\011\017\024\021\030\016" +
    "\001\002\000\012\011\017\024\021\026\102\030\016\001" +
    "\002\000\004\012\101\001\002\000\012\011\ufff4\024\ufff4" +
    "\026\ufff4\030\ufff4\001\002\000\004\030\105\001\002\000" +
    "\004\012\104\001\002\000\012\011\ufff3\024\ufff3\026\ufff3" +
    "\030\ufff3\001\002\000\004\012\ufff9\001\002\000\004\025" +
    "\107\001\002\000\010\011\017\024\021\030\016\001\002" +
    "\000\012\011\017\024\021\026\111\030\016\001\002\000" +
    "\004\012\ufff5\001\002\000\022\002\uffec\007\uffec\010\uffec" +
    "\022\uffec\023\uffec\024\uffec\027\uffec\030\uffec\001\002\000" +
    "\022\002\uffed\007\uffed\010\uffed\022\uffed\023\uffed\024\uffed" +
    "\027\uffed\030\uffed\001\002\000\004\002\000\001\002\000" +
    "\014\002\001\007\001\022\001\023\001\024\001\001\002" +
    "\000\022\002\uffee\007\uffee\010\uffee\022\uffee\023\uffee\024" +
    "\uffee\027\uffee\030\uffee\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\114\000\014\002\004\003\012\004\011\007\005\012" +
    "\013\001\001\000\002\001\001\000\012\003\114\004\011" +
    "\007\005\012\013\001\001\000\004\010\112\001\001\000" +
    "\002\001\001\000\006\006\072\011\073\001\001\000\010" +
    "\006\021\011\022\014\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\005\036\006\035\015" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\005\041\006\035\015\037\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\005\051\006\035" +
    "\015\037\001\001\000\010\005\046\006\035\015\037\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\016\061\001" +
    "\001\000\004\010\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\005\062\006\035\015\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\006\072\011\077\013\076\001\001" +
    "\000\006\006\072\011\102\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\006" +
    "\072\011\077\013\107\001\001\000\006\006\072\011\102" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



   
	public CodeGenerator cg = new CodeGenerator();

    public void report_error(String message, Object info) {
   
       
        StringBuilder m = new StringBuilder("Error");
   
        if (info instanceof Symbol) {
     
            Symbol s = ((Symbol) info);

            if (s.left >= 0) {                
                       m.append(" in line "+(s.left+1));   
     
                if (s.right >= 0)                    
                       m.append(", column "+(s.right+1));
            }
        }
   
        m.append(" : "+message);
   
        System.err.println(m);
    }
   
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ident ::= STRUCT ID STAR 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = "struct " + i + "*"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // ident ::= ident LPAREN STAR RPAREN 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object i = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 RESULT = i + " (*)"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // ident ::= ident LBRACKET RBRACKET 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object i = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = i + "[]"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // ident ::= ident STAR 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object i = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = i + "*"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ident ::= PRE_ID PRE_ID ID 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object i = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int i2left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int i2right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object i2 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int i3left = ((Symbol)CUP$parser$stack.peek()).left;
		int i3right = ((Symbol)CUP$parser$stack.peek()).right;
		String i3 = (String)((Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i + " " + i2 + " " + i3; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ident ::= PRE_ID ID 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object i = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int i2left = ((Symbol)CUP$parser$stack.peek()).left;
		int i2right = ((Symbol)CUP$parser$stack.peek()).right;
		String i2 = (String)((Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i + " " + i2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ident ::= ID 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.peek()).left;
		int iright = ((Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident",4, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ident_funcpointer ::= ident LPAREN params RPAREN 
            {
              Object RESULT =null;
		int p4left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int p4right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object p4 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ps2left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int ps2right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object ps2 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
			 RESULT = p4+"("+ps2+")"; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ident_funcpointer",11, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // params ::= 
            {
              Object RESULT =null;
		 RESULT = ""; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",3, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // params ::= ident_funcpointer COMMA params 
            {
              Object RESULT =null;
		int p5left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int p5right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object p5 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ps2left = ((Symbol)CUP$parser$stack.peek()).left;
		int ps2right = ((Symbol)CUP$parser$stack.peek()).right;
		Object ps2 = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p5 + " , " + ps2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",3, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // params ::= ident_funcpointer 
            {
              Object RESULT =null;
		int p4left = ((Symbol)CUP$parser$stack.peek()).left;
		int p4right = ((Symbol)CUP$parser$stack.peek()).right;
		Object p4 = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p4; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",3, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // params ::= ident COMMA DOTS 
            {
              Object RESULT =null;
		int p3left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int p3right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object p3 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
			 RESULT = p3; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",3, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // params ::= ident COMMA params 
            {
              Object RESULT =null;
		int p2left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int p2right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object p2 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int psleft = ((Symbol)CUP$parser$stack.peek()).left;
		int psright = ((Symbol)CUP$parser$stack.peek()).right;
		Object ps = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 
			RESULT = p2 + " , " + ps; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",3, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // params ::= ident 
            {
              Object RESULT =null;
		int pleft = ((Symbol)CUP$parser$stack.peek()).left;
		int pright = ((Symbol)CUP$parser$stack.peek()).right;
		Object p = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 
			RESULT = p; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",3, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // value ::= NUMBER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("value",6, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // value ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("value",6, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sharp_s ::= sharp_s NO_CARE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sharp_s",5, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sharp_s ::= sharp_s value 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sharp_s",5, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sharp_s ::= SHARP ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sharp_s",5, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // defin ::= ident LPAREN STAR ID RPAREN LPAREN params RPAREN 
            {
              Object RESULT =null;
		int i7left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int i7right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		Object i7 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int i8left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int i8right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i8 = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int psleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int psright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object ps = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
			parser.cg.dec.push(i7);
			parser.cg.dec.push(i8);
			parser.cg.dec.push("(" + ps + ")");
			RESULT = i7 + " (*" + i8 + ")(" + ps + ")"; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defin",7, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // defin ::= ident ID LBRACKET RBRACKET 
            {
              Object RESULT =null;
		int i5left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int i5right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object i5 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int i6left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int i6right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i6 = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
			parser.cg.dec.push(i5);
			parser.cg.dec.push(i6);
			parser.cg.dec.push("[]");
			RESULT = i5 + " " + i6 + "[]"; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defin",7, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // defin ::= ident ID LBRACKET value RBRACKET 
            {
              Object RESULT =null;
		int i3left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int i3right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object i3 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int i4left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int i4right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i4 = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object v = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
			parser.cg.dec.push(i3);
			parser.cg.dec.push(i4);
			parser.cg.dec.push("["+v+"]");
			RESULT = i3 + " " + i4 + "[" + v + "]"; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defin",7, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // defin ::= ident ID 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object i = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int i2left = ((Symbol)CUP$parser$stack.peek()).left;
		int i2right = ((Symbol)CUP$parser$stack.peek()).right;
		String i2 = (String)((Symbol) CUP$parser$stack.peek()).value;
		 
			parser.cg.dec.push(i);
			parser.cg.dec.push(i2);
			RESULT = i + " " + i2; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defin",7, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // st_body ::= st_body defin SEMI 
            {
              Object RESULT =null;
		int sleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object s = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int d2left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int d2right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object d2 = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = s + "\n" + d2 + ";" ; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("st_body",9, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // st_body ::= defin SEMI 
            {
              Object RESULT =null;
		int dleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object d = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = d + ";"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("st_body",9, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // _struct ::= STRUCT ID LQ st_body RQ 
            {
              Object RESULT =null;
		int ileft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object s = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
			parser.cg.s.setName(i);
			RESULT = "struct " + i + "{" + "\n" + s + "\n" + "};"; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("_struct",8, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // func ::= ident ID LPAREN NT$0 params RPAREN 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object e = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int e2left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int e2right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String e2 = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int pleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object p = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
			parser.cg.f.pushParam(p);
			RESULT = e + " " + e2 + "(" + p + ");"; 
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",10, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // NT$0 ::= 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e2right = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e2 = (String)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 
			parser.cg.f.setReturn_type(e);
			parser.cg.f.setID(e2);
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",12, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= _struct 
            {
              Object RESULT =null;
		int sleft = ((Symbol)CUP$parser$stack.peek()).left;
		int sright = ((Symbol)CUP$parser$stack.peek()).right;
		Object s = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 parser.cg.declareStruct(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",2, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= TYPEDEF STRUCT LQ st_body RQ ID 
            {
              Object RESULT =null;
		int sleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object s = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((Symbol)CUP$parser$stack.peek()).left;
		int iright = ((Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((Symbol) CUP$parser$stack.peek()).value;
		 parser.cg.declareTypedef_struct(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= TYPEDEF defin 
            {
              Object RESULT =null;
		int d2left = ((Symbol)CUP$parser$stack.peek()).left;
		int d2right = ((Symbol)CUP$parser$stack.peek()).right;
		Object d2 = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 parser.cg.declareTypedef_var(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= EXTERN defin 
            {
              Object RESULT =null;
		int dleft = ((Symbol)CUP$parser$stack.peek()).left;
		int dright = ((Symbol)CUP$parser$stack.peek()).right;
		Object d = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 parser.cg.declareVar(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= EXTERN func 
            {
              Object RESULT =null;
		int fleft = ((Symbol)CUP$parser$stack.peek()).left;
		int fright = ((Symbol)CUP$parser$stack.peek()).right;
		Object f = (Object)((Symbol) CUP$parser$stack.peek()).value;
		 parser.cg.declareFunc(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",2, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr_part ::= sharp_s 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_part",1, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr_part ::= expr SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_part",1, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr_list ::= expr_part 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((Symbol)CUP$parser$stack.peek()), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr_list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr_list ::= expr_list expr_part 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

