package stdioImporter.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ImportConfig_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ImportConfig_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "stdioImporter.structure.ImportConfig";
  }
}
