package stdioImporter.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ImportConfigs_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ImportConfigs_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "stdioImporter.structure.ImportConfigs";
  }
}
