package stdioImporter.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import stdioImporter.runtime.Importer;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ImportConfig_Behavior {
  public static void init(SNode thisNode) {
  }
  public static String call_getFileName_3873900481303667412(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(0x4552c9e5a3424299L, 0x8de1338d8e5679fcL, 0x35c2dbf6834d5c11L, 0x35c2dbf6834d95d2L, "filename"));
  }
  public static String call_getContainingFolder_233004638652596833(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(0x4552c9e5a3424299L, 0x8de1338d8e5679fcL, 0x35c2dbf6834d5c11L, 0x33bcc7bfde7a0b3L, "containingfolder"));
  }
  public static boolean call_performImport_3873900481303708928(SNode thisNode) {
    return Importer.doImport(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getReferenceLink(0x4552c9e5a3424299L, 0x8de1338d8e5679fcL, 0x35c2dbf6834d5c11L, 0x35c2dbf6834d97beL, "module")), ImportConfig_Behavior.call_getFileName_3873900481303667412(thisNode), ImportConfig_Behavior.call_getContainingFolder_233004638652596833(thisNode));
  }
}
