package stdioImporter.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class null_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public null_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "stdioImporter.structure.null";
  }
}
