package stdioImporter.runtime;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.backports.Deque;

public class ExpMaker {
  /*package*/ List<String> operands;

  public ExpMaker() {
    ListSequence.fromList(operands).addElement("++");
    ListSequence.fromList(operands).addElement("--");
    ListSequence.fromList(operands).addElement("(");
    ListSequence.fromList(operands).addElement("[");
    ListSequence.fromList(operands).addElement(".");
    ListSequence.fromList(operands).addElement("->");
    ListSequence.fromList(operands).addElement("+");
    ListSequence.fromList(operands).addElement("-");





  }

  public SNode makeExp() {
    String exp;
    Deque<String> ostack;
    return null;
  }
}
