package stdioImporter.runtime;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import stdio_parser.CodeGenerator;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Importer {
  public static boolean doImport(SNode module, String filename) {
    try {
      CodeGenerator cg = ParserAdapter.Parse(filename);
      if (cg == null) {
        return false;
      }

      SNode header = SConceptOperations.createNewNode("com.mbeddr.core.modules.structure.HeaderDescriptor", null);
      SPropertyOperations.set(header, "path", "\"" + filename + "\"");
      ListSequence.fromList(SLinkOperations.getTargets(module, "descriptors", true)).addElement(header);

      ImporterCore core = new ImporterCore();
      core.addDeclarations(cg.declarations, module);

    } catch (Exception e) {
      return false;
    }
    return true;
  }
}
