package stdioImporter.runtime;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Typer {
  public SNode buildType(String type, Iterable<SNode> typedefs) {
    if (type.endsWith("*")) {
      int i = type.length() - type.indexOf("*") - 1;
      String basetype = type.substring(0, type.indexOf("*"));
      return this.makePointerType(this.buildType(basetype, typedefs), i);
    }

    {
      Iterator<SNode> t_it = Sequence.fromIterable(typedefs).iterator();
      SNode t_var;
      while (t_it.hasNext()) {
        t_var = t_it.next();
        if (SPropertyOperations.getString(t_var, "name").equals(type)) {
          SNode tdt = SConceptOperations.createNewNode("com.mbeddr.core.udt.structure.TypeDefType", null);
          SLinkOperations.setTarget(tdt, "typeDef", t_var, false);
          return tdt;
        }
      }
    }
    return this.mapType(type);
  }



  private SNode makePointerType(SNode basetype, int n) {
    SNode ptype = SConceptOperations.createNewNode("com.mbeddr.core.pointers.structure.PointerType", null);
    SLinkOperations.setTarget(ptype, "baseType", basetype, true);
    for (int i = 0; i < n; i++) {
      SNode temp = ptype;
      ptype = SConceptOperations.createNewNode("com.mbeddr.core.pointers.structure.PointerType", null);
      SLinkOperations.setTarget(ptype, "baseType", temp, true);
    }
    return ptype;
  }

  private SNode mapType(String type) {
    if (type.startsWith("int")) {
      return SConceptOperations.createNewNode("com.mbeddr.core.expressions.structure.IntType", null);
    } else if (type.startsWith("unsigned int")) {
      return SConceptOperations.createNewNode("com.mbeddr.core.expressions.structure.UnsignedIntType", null);
    } else if (type.startsWith("char")) {
      return SConceptOperations.createNewNode("com.mbeddr.core.expressions.structure.CharType", null);
    } else if (type.startsWith("unsigned char")) {
      return SConceptOperations.createNewNode("com.mbeddr.core.expressions.structure.UnsignedCharType", null);
    }
    return null;
  }




}
